import { PresentationSummaryData } from '../types/markdownExport';

export function generateSlideDeckMarkdown(data: PresentationSummaryData): string {
  return [
    `# 📊 Presentation Deck Summary: ${data.title}`,
    ``,
    `*Generated by ScreenCanvas on ${data.timestamp}*`,
    ``,
    `- **Total Slides**: ${data.totalSlides}`,
    `- **Total Annotations & Drawings**: ${data.totalElements}`,
    `- **Author**: ${data.author || 'ScreenCanvas Presenter'}`,
    ``,
    `---`,
    `*Created with ScreenCanvas desktop annotation suite.*`,
  ].join('\n');
}
